### PR TITLE
Add a custom node tutorial to the readme

### PR DESCRIPTION
**Pull request by Jummit**
Still WIP, any suggestions?

### CODE REVIEW

**Comment by swarnimarun** [comment]
Seems nice. up up... and it's merged...  😉

**Comment by swarnimarun** [comment]
Joking feel free to ask me to merge when you feel like it.

**Comment by Jummit** [comment]
> Joking feel free to ask me to merge when you feel like it.

Will do!

**Comment by Jummit** [comment]
Don't know what I wanted to do anymore, so just merge it. #noregrets
@swarnimarun

**Comment by follower** [comment]
FWIW IMO this GDScript custom node tutorial would be a great addition to the official documentation--I'd encourage you to consider submitting a PR there too. :)

**Comment by Jummit** [comment]
> FWIW IMO this GDScript custom node tutorial would be a great addition to the official documentation--I'd encourage you to consider submitting a PR there too. :)

Here you go: godotengine/godot-docs#3289

**Comment by follower** [comment]
> Here you go: godotengine/godot-docs#3289

Awesome, thanks!

**Pull request merged**
