### PR TITLE
Add load directory node

### PR DESCRIPTION
**Pull request by Jummit**
Used to load all loadable files inside a directory into a dictionary with keys being the file names without extension and values being the loaded objects. This is not recursive (atm).

### CODE REVIEW

**Comment by swarnimarun** [comment]
Thanks for the PR. BTW. Would you like to also do a very tiny explanation on how to use it and put it in the Readme. 
I haven't done it for the nodes I created but I feel like a couple sentences would do good for this one as the use case is a little more confusing. 

If you want to just add it to the PR and I will merge it.

**Comment by swarnimarun** [comment]
Let me know what you decide. :)

**Comment by Jummit** [comment]
@swarnimarun Done. I also made some grammar corrections and enhancements in the readme if you don't mind :D

**Comment by swarnimarun** [comment]
Awesome man. Appreciate the effort. :)

**Pull request merged**
