### PR TITLE
Add reroute node

### PR DESCRIPTION
**Pull request by Jummit**
Super simple but super powerful! Has a sequence and a data mode.
image

### CODE REVIEW

**Comment by swarnimarun** [comment]
Really nice idea.

Uhm... I seriously feel like it should be similar to Blender's reroute point. 

Will add it into the Godot Visual Script module once I have some free time. (After my exams)

Until then just check the line note I have left, after that I will merge it. 😊

**Comment by fire** [comment]
This is being worked on here.

https://github.com/godotengine/godot/pull/28443#issuecomment-487025230

The approach is that a reroute node is a minimized node changed into a point.

**Comment by fire** [comment]
The idea is that the reroute node is three things:

https://github.com/godotengine/godot/pull/22869

1. Creating the reroute node
1. Minimizing it so it's a point
1. Adding a click on spline and delete from spline.

**Comment by Chaosus** [comment]
@Jummit This can be more compact if you've added new functionality to GraphNode but nevermind. Can you do the same for Visual Shaders ?

**Comment by swarnimarun** [comment]
@Chaosus I don't remember there being a way to add custom nodes to Visual Shader Editor so I am gonna say No.

**Comment by swarnimarun** [comment]
Will have to directly edit the GraphNode code to add a way to achieve this.

**Comment by Chaosus** [comment]
Nvm, I didnt take attention that it's not a Godot repo :) sorry

**Pull request merged**
