### PR TITLE
Add a flexible random node

### PR DESCRIPTION
**Pull request by Jummit**
A better version of the old random node, allows for ints, floats, Vector2s and Vector3s. I'm not sure about the naming, maybe it should be called flexibleRandom or something like that.

### CODE REVIEW

**Comment by swarnimarun** [comment]
Rename it to something starting with Random as at least the search in the current and older versions will allow to find it easily.

**Comment by swarnimarun** [comment]
Random Node, Random Multi Node anything works

**Comment by Jummit** [comment]
Changed the name to "Advanced Random" node. Ready to merge.

**Comment by swarnimarun** [comment]
nice

**Pull request merged**
